name: build

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [1.18, 1.x]

    name: Go ${{ matrix.go }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: make build

      - name: Run tests
        run: make test
